// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Params []string   `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	Req    *ClientMsg `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Error) GetReq() *ClientMsg {
	if x != nil {
		return x.Req
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Seq int32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// event create time (from business server), unix timestamp seconds.
	CreateTime int64  `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Payload    string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                       // json format message
	ReadState  bool   `protobuf:"varint,5,opt,name=read_state,json=readState,proto3" json:"read_state,omitempty"` // true: read, false: unread
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Event) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetReadState() bool {
	if x != nil {
		return x.ReadState
	}
	return false
}

// server sid event config.
type WsConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the max TTL of any events in backend store.
	EventTtlDays    int32 `protobuf:"varint,1,opt,name=event_ttl_days,json=eventTtlDays,proto3" json:"event_ttl_days,omitempty"`
	GetEventsLimit  int32 `protobuf:"varint,2,opt,name=get_events_limit,json=getEventsLimit,proto3" json:"get_events_limit,omitempty"`
	EnableClientMsg bool  `protobuf:"varint,3,opt,name=enable_client_msg,json=enableClientMsg,proto3" json:"enable_client_msg,omitempty"`
	MaxMsgSize      int32 `protobuf:"varint,4,opt,name=max_msg_size,json=maxMsgSize,proto3" json:"max_msg_size,omitempty"` // 4096 bytes
}

func (x *WsConf) Reset() {
	*x = WsConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WsConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsConf) ProtoMessage() {}

func (x *WsConf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsConf.ProtoReflect.Descriptor instead.
func (*WsConf) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *WsConf) GetEventTtlDays() int32 {
	if x != nil {
		return x.EventTtlDays
	}
	return 0
}

func (x *WsConf) GetGetEventsLimit() int32 {
	if x != nil {
		return x.GetEventsLimit
	}
	return 0
}

func (x *WsConf) GetEnableClientMsg() bool {
	if x != nil {
		return x.EnableClientMsg
	}
	return false
}

func (x *WsConf) GetMaxMsgSize() int32 {
	if x != nil {
		return x.MaxMsgSize
	}
	return 0
}

// get events request. to_seq - to_seq must < Config.get_events_limit
type GetEventsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromSeq int32 `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // inclusive
	ToSeq   int32 `protobuf:"varint,2,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"`       // inclusive
}

func (x *GetEventsReq) Reset() {
	*x = GetEventsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsReq) ProtoMessage() {}

func (x *GetEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsReq.ProtoReflect.Descriptor instead.
func (*GetEventsReq) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventsReq) GetFromSeq() int32 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *GetEventsReq) GetToSeq() int32 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

type GetEventsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// actual events returned from server, order by seq DESC.
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *GetEventsResp) Reset() {
	*x = GetEventsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResp) ProtoMessage() {}

func (x *GetEventsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResp.ProtoReflect.Descriptor instead.
func (*GetEventsResp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsResp) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// stat events request.
type StatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// optional count unread events.
	CountUnread bool `protobuf:"varint,1,opt,name=count_unread,json=countUnread,proto3" json:"count_unread,omitempty"`
}

func (x *StatsReq) Reset() {
	*x = StatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReq) ProtoMessage() {}

func (x *StatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReq.ProtoReflect.Descriptor instead.
func (*StatsReq) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *StatsReq) GetCountUnread() bool {
	if x != nil {
		return x.CountUnread
	}
	return false
}

type StatsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conf    *WsConf `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	HeadSeq int32   `protobuf:"varint,2,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	// valid only if `StatsReq.count_unread` is true
	UnreadCount int32 `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
}

func (x *StatsResp) Reset() {
	*x = StatsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResp) ProtoMessage() {}

func (x *StatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResp.ProtoReflect.Descriptor instead.
func (*StatsResp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *StatsResp) GetConf() *WsConf {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *StatsResp) GetHeadSeq() int32 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *StatsResp) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// Get read states request.
type GetReadStatesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// get read states of events with seq <= this value.
	HeadSeq int32 `protobuf:"varint,1,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
}

func (x *GetReadStatesReq) Reset() {
	*x = GetReadStatesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadStatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadStatesReq) ProtoMessage() {}

func (x *GetReadStatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadStatesReq.ProtoReflect.Descriptor instead.
func (*GetReadStatesReq) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetReadStatesReq) GetHeadSeq() int32 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

type GetReadStatesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*GetReadStatesResp_Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *GetReadStatesResp) Reset() {
	*x = GetReadStatesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadStatesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadStatesResp) ProtoMessage() {}

func (x *GetReadStatesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadStatesResp.ProtoReflect.Descriptor instead.
func (*GetReadStatesResp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetReadStatesResp) GetBlocks() []*GetReadStatesResp_Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// SetReadReq sets given event's state as `read`.
type SetReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sequence
	Seq int32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *SetReadReq) Reset() {
	*x = SetReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadReq) ProtoMessage() {}

func (x *SetReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReadReq.ProtoReflect.Descriptor instead.
func (*SetReadReq) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *SetReadReq) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SetReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sequence
	Seq int32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// true means the event was updated from unread to read.
	Changed bool `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
}

func (x *SetReadResp) Reset() {
	*x = SetReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadResp) ProtoMessage() {}

func (x *SetReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReadResp.ProtoReflect.Descriptor instead.
func (*SetReadResp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *SetReadResp) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SetReadResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

// ClientMsg is the message from websocket client.
// Must set one of the fields.
type ClientMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats         *StatsReq         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	GetEvents     *GetEventsReq     `protobuf:"bytes,2,opt,name=get_events,json=getEvents,proto3" json:"get_events,omitempty"`
	SetRead       *SetReadReq       `protobuf:"bytes,3,opt,name=set_read,json=setRead,proto3" json:"set_read,omitempty"`
	GetReadStates *GetReadStatesReq `protobuf:"bytes,4,opt,name=get_read_states,json=getReadStates,proto3" json:"get_read_states,omitempty"`
	Im            *E2EMsg           `protobuf:"bytes,5,opt,name=im,proto3" json:"im,omitempty"`
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *ClientMsg) GetStats() *StatsReq {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ClientMsg) GetGetEvents() *GetEventsReq {
	if x != nil {
		return x.GetEvents
	}
	return nil
}

func (x *ClientMsg) GetSetRead() *SetReadReq {
	if x != nil {
		return x.SetRead
	}
	return nil
}

func (x *ClientMsg) GetGetReadStates() *GetReadStatesReq {
	if x != nil {
		return x.GetReadStates
	}
	return nil
}

func (x *ClientMsg) GetIm() *E2EMsg {
	if x != nil {
		return x.Im
	}
	return nil
}

// ServerMsg is the message from websocket server.
// Must set one of the fields.
type ServerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error         *Error             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	HeadSeq       int32              `protobuf:"varint,2,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	Kickoff       bool               `protobuf:"varint,3,opt,name=kickoff,proto3" json:"kickoff,omitempty"`
	Stats         *StatsResp         `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	GetEvents     *GetEventsResp     `protobuf:"bytes,5,opt,name=get_events,json=getEvents,proto3" json:"get_events,omitempty"`
	GetReadStates *GetReadStatesResp `protobuf:"bytes,6,opt,name=get_read_states,json=getReadStates,proto3" json:"get_read_states,omitempty"`
	SetRead       *SetReadResp       `protobuf:"bytes,7,opt,name=set_read,json=setRead,proto3" json:"set_read,omitempty"`
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *ServerMsg) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServerMsg) GetHeadSeq() int32 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *ServerMsg) GetKickoff() bool {
	if x != nil {
		return x.Kickoff
	}
	return false
}

func (x *ServerMsg) GetStats() *StatsResp {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ServerMsg) GetGetEvents() *GetEventsResp {
	if x != nil {
		return x.GetEvents
	}
	return nil
}

func (x *ServerMsg) GetGetReadStates() *GetReadStatesResp {
	if x != nil {
		return x.GetReadStates
	}
	return nil
}

func (x *ServerMsg) GetSetRead() *SetReadResp {
	if x != nil {
		return x.SetRead
	}
	return nil
}

// Session is a memory user session.
type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hub id, new UUID on start.
	HubId string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	// user id
	Uid int32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// session id
	Sid string `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	// client ip
	Ip string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	// create time (unix timestamp)
	CreateTime int64 `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// kickoff time
	KickoffTime int64 `protobuf:"varint,6,opt,name=kickoff_time,json=kickoffTime,proto3" json:"kickoff_time,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *Session) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *Session) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Session) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Session) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Session) GetKickoffTime() int64 {
	if x != nil {
		return x.KickoffTime
	}
	return 0
}

// End to end message: server -> user, user -> server -> user.
type E2EMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`     // business type for push.
	From  int32             `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`    // from uid, optional
	To    []int32           `protobuf:"varint,3,rep,packed,name=to,proto3" json:"to,omitempty"` // to uids.
	Props map[string]string `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body  string            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *E2EMsg) Reset() {
	*x = E2EMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2EMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2EMsg) ProtoMessage() {}

func (x *E2EMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2EMsg.ProtoReflect.Descriptor instead.
func (*E2EMsg) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *E2EMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *E2EMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *E2EMsg) GetTo() []int32 {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *E2EMsg) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *E2EMsg) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// FollowerMsg is the message sent from cluster follower to cluster leader.
type FollowerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// an online session.
	SessionOnline *Session `protobuf:"bytes,1,opt,name=session_online,json=sessionOnline,proto3" json:"session_online,omitempty"`
	// sid of an offline session.
	SessionOffline string `protobuf:"bytes,2,opt,name=session_offline,json=sessionOffline,proto3" json:"session_offline,omitempty"`
	// sync to leader
	SyncSessions []*Session `protobuf:"bytes,3,rep,name=sync_sessions,json=syncSessions,proto3" json:"sync_sessions,omitempty"`
	// this follower is shutting down.
	ServerShutdown bool `protobuf:"varint,4,opt,name=server_shutdown,json=serverShutdown,proto3" json:"server_shutdown,omitempty"`
	// e2e im message.
	E2EMsg *E2EMsg `protobuf:"bytes,5,opt,name=e2e_msg,json=e2eMsg,proto3" json:"e2e_msg,omitempty"`
}

func (x *FollowerMsg) Reset() {
	*x = FollowerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerMsg) ProtoMessage() {}

func (x *FollowerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerMsg.ProtoReflect.Descriptor instead.
func (*FollowerMsg) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *FollowerMsg) GetSessionOnline() *Session {
	if x != nil {
		return x.SessionOnline
	}
	return nil
}

func (x *FollowerMsg) GetSessionOffline() string {
	if x != nil {
		return x.SessionOffline
	}
	return ""
}

func (x *FollowerMsg) GetSyncSessions() []*Session {
	if x != nil {
		return x.SyncSessions
	}
	return nil
}

func (x *FollowerMsg) GetServerShutdown() bool {
	if x != nil {
		return x.ServerShutdown
	}
	return false
}

func (x *FollowerMsg) GetE2EMsg() *E2EMsg {
	if x != nil {
		return x.E2EMsg
	}
	return nil
}

// LeaderMsg is the message sent from cluster leader to cluster follower.
type LeaderMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// map from uid to head sequence, leader -> followers -> users.
	HeadSeq map[int32]int32 `protobuf:"bytes,1,rep,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// session ids to kickoff.
	Kickoff []string `protobuf:"bytes,2,rep,name=kickoff,proto3" json:"kickoff,omitempty"`
	// leader is shutting down.
	ServerShutdown bool `protobuf:"varint,3,opt,name=server_shutdown,json=serverShutdown,proto3" json:"server_shutdown,omitempty"`
}

func (x *LeaderMsg) Reset() {
	*x = LeaderMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderMsg) ProtoMessage() {}

func (x *LeaderMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderMsg.ProtoReflect.Descriptor instead.
func (*LeaderMsg) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *LeaderMsg) GetHeadSeq() map[int32]int32 {
	if x != nil {
		return x.HeadSeq
	}
	return nil
}

func (x *LeaderMsg) GetKickoff() []string {
	if x != nil {
		return x.Kickoff
	}
	return nil
}

func (x *LeaderMsg) GetServerShutdown() bool {
	if x != nil {
		return x.ServerShutdown
	}
	return false
}

type GetReadStatesResp_Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the beginning(max) sequence in the block.
	Seq int32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// length of raw(un-encoded) read states bool array.
	Len int32 `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	// encoded read states:
	// bool array -> byte array (BIG endian) -> standard base64.
	// order by seq DESC.
	Base64 string `protobuf:"bytes,3,opt,name=base64,proto3" json:"base64,omitempty"`
}

func (x *GetReadStatesResp_Block) Reset() {
	*x = GetReadStatesResp_Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadStatesResp_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadStatesResp_Block) ProtoMessage() {}

func (x *GetReadStatesResp_Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadStatesResp_Block.ProtoReflect.Descriptor instead.
func (*GetReadStatesResp_Block) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetReadStatesResp_Block) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetReadStatesResp_Block) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *GetReadStatesResp_Block) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

var File_proto_api_proto protoreflect.FileDescriptor

var file_proto_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x22, 0x5a, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x25, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x85, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0xa6, 0x01, 0x0a, 0x06, 0x57, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x24, 0x0a, 0x0e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x74, 0x6c, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x74, 0x6c, 0x44, 0x61, 0x79, 0x73,
	0x12, 0x28, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x67, 0x65, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61,
	0x78, 0x4d, 0x73, 0x67, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d,
	0x53, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x53, 0x65, 0x71, 0x22, 0x38, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x06, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x69,
	0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x2d, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x22, 0x6f, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x24, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x57, 0x73, 0x43, 0x6f, 0x6e, 0x66,
	0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x73,
	0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x53, 0x65,
	0x71, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x64,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x53, 0x65, 0x71, 0x22, 0x93, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x06, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x69, 0x6e, 0x69,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x1a, 0x43, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6c, 0x65,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x22, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x39, 0x0a, 0x0b, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x64, 0x22, 0x83, 0x02, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0a,
	0x67, 0x65, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x52, 0x09, 0x67, 0x65, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x52, 0x07, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x12, 0x42, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x52, 0x0d, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x02, 0x69, 0x6d, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x45, 0x32, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x02, 0x69, 0x6d, 0x22, 0xc1, 0x02, 0x0a, 0x09, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75,
	0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x53, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x69,
	0x63, 0x6b, 0x6f, 0x66, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6b, 0x69, 0x63,
	0x6b, 0x6f, 0x66, 0x66, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x36, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x47,
	0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x52, 0x09, 0x67, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x43, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0d, 0x67,
	0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08,
	0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x07, 0x73, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x22, 0x98,
	0x01, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75,
	0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x69, 0x63, 0x6b, 0x6f, 0x66,
	0x66, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6b, 0x69,
	0x63, 0x6b, 0x6f, 0x66, 0x66, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x06, 0x45, 0x32,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x31, 0x0a, 0x05,
	0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69,
	0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x32, 0x65, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x1a, 0x38, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xfc, 0x01,
	0x0a, 0x0b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x38, 0x0a,
	0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68,
	0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x36, 0x0a, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75,
	0x73, 0x68, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x79, 0x6e, 0x63,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x12, 0x29, 0x0a, 0x07, 0x65, 0x32, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x32,
	0x65, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x65, 0x32, 0x65, 0x4d, 0x73, 0x67, 0x22, 0xc7, 0x01, 0x0a,
	0x09, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x3b, 0x0a, 0x08, 0x68, 0x65,
	0x61, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d,
	0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x53, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x53, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x69, 0x63, 0x6b, 0x6f,
	0x66, 0x66, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x69, 0x63, 0x6b, 0x6f, 0x66,
	0x66, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x75, 0x74,
	0x64, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65,
	0x61, 0x64, 0x53, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x4c, 0x0a, 0x0f, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x75,
	0x73, 0x68, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x05, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x1a, 0x13, 0x2e, 0x6d, 0x69, 0x6e, 0x69,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x71, 0x79, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x75, 0x73, 0x68, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData = file_proto_api_proto_rawDesc
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_proto_rawDescData)
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_api_proto_goTypes = []interface{}{
	(*Error)(nil),                   // 0: minipush.Error
	(*Event)(nil),                   // 1: minipush.Event
	(*WsConf)(nil),                  // 2: minipush.WsConf
	(*GetEventsReq)(nil),            // 3: minipush.GetEventsReq
	(*GetEventsResp)(nil),           // 4: minipush.GetEventsResp
	(*StatsReq)(nil),                // 5: minipush.StatsReq
	(*StatsResp)(nil),               // 6: minipush.StatsResp
	(*GetReadStatesReq)(nil),        // 7: minipush.GetReadStatesReq
	(*GetReadStatesResp)(nil),       // 8: minipush.GetReadStatesResp
	(*SetReadReq)(nil),              // 9: minipush.SetReadReq
	(*SetReadResp)(nil),             // 10: minipush.SetReadResp
	(*ClientMsg)(nil),               // 11: minipush.ClientMsg
	(*ServerMsg)(nil),               // 12: minipush.ServerMsg
	(*Session)(nil),                 // 13: minipush.Session
	(*E2EMsg)(nil),                  // 14: minipush.E2eMsg
	(*FollowerMsg)(nil),             // 15: minipush.FollowerMsg
	(*LeaderMsg)(nil),               // 16: minipush.LeaderMsg
	(*GetReadStatesResp_Block)(nil), // 17: minipush.GetReadStatesResp.Block
	nil,                             // 18: minipush.E2eMsg.PropsEntry
	nil,                             // 19: minipush.LeaderMsg.HeadSeqEntry
}
var file_proto_api_proto_depIdxs = []int32{
	11, // 0: minipush.Error.req:type_name -> minipush.ClientMsg
	1,  // 1: minipush.GetEventsResp.events:type_name -> minipush.Event
	2,  // 2: minipush.StatsResp.conf:type_name -> minipush.WsConf
	17, // 3: minipush.GetReadStatesResp.blocks:type_name -> minipush.GetReadStatesResp.Block
	5,  // 4: minipush.ClientMsg.stats:type_name -> minipush.StatsReq
	3,  // 5: minipush.ClientMsg.get_events:type_name -> minipush.GetEventsReq
	9,  // 6: minipush.ClientMsg.set_read:type_name -> minipush.SetReadReq
	7,  // 7: minipush.ClientMsg.get_read_states:type_name -> minipush.GetReadStatesReq
	14, // 8: minipush.ClientMsg.im:type_name -> minipush.E2eMsg
	0,  // 9: minipush.ServerMsg.error:type_name -> minipush.Error
	6,  // 10: minipush.ServerMsg.stats:type_name -> minipush.StatsResp
	4,  // 11: minipush.ServerMsg.get_events:type_name -> minipush.GetEventsResp
	8,  // 12: minipush.ServerMsg.get_read_states:type_name -> minipush.GetReadStatesResp
	10, // 13: minipush.ServerMsg.set_read:type_name -> minipush.SetReadResp
	18, // 14: minipush.E2eMsg.props:type_name -> minipush.E2eMsg.PropsEntry
	13, // 15: minipush.FollowerMsg.session_online:type_name -> minipush.Session
	13, // 16: minipush.FollowerMsg.sync_sessions:type_name -> minipush.Session
	14, // 17: minipush.FollowerMsg.e2e_msg:type_name -> minipush.E2eMsg
	19, // 18: minipush.LeaderMsg.head_seq:type_name -> minipush.LeaderMsg.HeadSeqEntry
	15, // 19: minipush.MiniPushCluster.Route:input_type -> minipush.FollowerMsg
	16, // 20: minipush.MiniPushCluster.Route:output_type -> minipush.LeaderMsg
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WsConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReadStatesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReadStatesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2EMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReadStatesResp_Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_rawDesc = nil
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
